class WorldData {
    static readonly screenMode: number; // = 0; 移动端屏幕布局模式
    static readonly sceneBGMGradientTime: number; // = 0; BGM过渡时间
    static readonly sceneBGSGradientTime: number; // = 0; BGS过渡时间
    static moveToGridCenter: boolean; // = false; 移动至格子中心点
    static readonly moveDir4: boolean; // = false; 四方向移动
    static readonly jumpTimeCost: number; // = 0; 跳跃花费的时间
    static readonly jumpHeight: number; // = 0; 跳跃高度
    static menuEnabled: boolean; // = true;
    static readonly sceneObjectCollisionSize: number; // = 32; 场景对象碰撞范围
    static readonly sceneObjectMoveStartAct: number; // = 2; 行走动作
    static readonly useSceneObjectMoveStartAct2: boolean; // = false; 开启奔跑动作
    static readonly sceneObjectMoveStartAct2Speed: number; // = 0; 奔跑时的速度
    static readonly sceneObjectMoveStartAct2: number; // = 0; 奔跑动作
    static readonly selectSceneObjectEffect: number; // = 0; 场景对象悬停动画
    static readonly saveFileMax: number; // = 10; 存档总数
    static playCtrlEnabled: boolean; // = true;
    static readonly uiCompFocusAnimation: number; // = 0; 界面组件焦点动画
    static gridObsDebug: boolean; // = false; 显示地图格子障碍
    static rectObsDebug: boolean; // = false; 显示对象碰撞盒
    static dragSceneObjectDebug: boolean; // = false; 鼠标左键拖拽对象
    static zoomCameraDebug: boolean; // = false; 滚轮缩放镜头
    static readonly focusEnabled: boolean; // = false; 使用按钮焦点
    static readonly hotKeyListEnabled: boolean; // = false; 允许按键操作列表
    static readonly sceneObjectMoveStartAct2FPS: number; // = 20; 奔跑时的帧率
    static readonly banCollisionSetting: DataStructure_collisionGroupSetting[]; // = [];
    static readonly selectSE: string; // = ""; 光标
    static readonly sureSE: string; // = ""; 确定
    static readonly cancelSE: string; // = ""; 取消
    static readonly disalbeSE: string; // = ""; 禁用
    static readonly dialogSE: string; // = ""; 文本播放音效
    static dialogSEEnabled: boolean; // = true;
    static readonly equipSE: string; // = ""; 穿上装备
    static readonly unequipSE: string; // = ""; 卸下装备
    static keyboards: DataStructure_gameKeyboard[]; // = [];
    static word_cost: string; // = ""; 消耗
    static word_gamepadInput: string; // = ""; 请按下游戏手柄键位
    static word_keyboardInput: string; // = ""; 请输入键盘键位
    static word_get: string; // = ""; 获得
    static word_turn: string; // = ""; 回合
    static word_bc1: string; // = ""; 以下任意角色阵亡
    static word_bc2: string; // = ""; 我方全员阵亡
    static word_used: string; // = ""; 使用了
    static word_usedAtk: string; // = ""; 发起了普通攻击
    static word_maxHP: string; // = ""; 最大生命值
    static word_maxSP: string; // = ""; 最大魔法值
    static word_atk: string; // = ""; 攻击力
    static word_def: string; // = ""; 防御
    static word_mag: string; // = ""; 魔力
    static word_magDef: string; // = ""; 魔法防御力
    static word_hit: string; // = ""; 命中
    static word_crit: string; // = ""; 暴击
    static word_magCrit: string; // = ""; 魔法暴击率
    static word_hp: string; // = ""; 生命值
    static word_sp: string; // = ""; 魔法值
    static word_moveGrid: string; // = ""; 移动力
    static word_dod: string; // = ""; 回避
    static actorItemMax: number; // = 2; 角色可携带道具数
    static readonly actorItemAllowToOthers: boolean; // = false; 道具允许对他人使用
    static bak1: number; // = 0; 准备阶段角色上场提示
    static bak2: number; // = 0; 准备阶段更换角色位置提示
    static bak3: number; // = 0; 准备阶段移动端提示
    static readyStepChangeOriEnabled: boolean; // = false; 准备阶段允许更换角色朝向
    static bak4: string; // = ""; 准备阶段更换角色朝向提示
    static standbyStepChangeOriEnabled: boolean; // = false; 待机阶段允许更换角色朝向
    static deadPlayerActorLeaveParty: boolean; // = true; 死亡的玩家角色将会离开队伍
    static readonly iconDisabledAni: number; // = 1; 图标禁用时动画效果
    static useItemActID: number; // = 1; 使用道具的动作
    static cameraTweenFrame: number; // = 0; 镜头移动花费时间
    static actionReflectionTime: number; // = 0; 电脑每次行动的思考时间
    static noActionWaitTime: number; // = 0; 电脑无行动时的等待时间
    static cursorSpeedByPlayerControl: number; // = 0; 玩家操控时光标移动速度
    static cursorSpeedByComputerControl: number; // = 0; 电脑操控时光标移动速度
    static aiOpenIndicator: boolean; // = false; 电脑行动时显示指示器
    static equipQualitySetting: DataStructure_equipQualitySetting[]; // = [];
    static getEXPMode: number; // = 0; 获得经验值方式
    static BackwardAttackDamagePer: number; // = 200; 背后攻击伤害比例（%）
    static battleReadyBGM: string; // = ""; 准备阶段背景音乐
    static battleBGM: string; // = ""; 战斗背景音乐
    static battleWinSE: string; // = ""; 战斗胜利音效
    static battleLoseSE: string; // = ""; 战斗失败音效
    static moveCalcTeammateObstacles: boolean; // = false; 移动时我方成员视为障碍
    static deadBattlerObstacles: boolean; // = false; 死亡的战斗者视为障碍
    static freePlayerTurnOrderEnabled: boolean; // = true; 玩家回合自由选择角色
    static fullStateWhenBattleStart: boolean; // = false; 战斗开始时完全恢复
    static readonly readyBattlerFieldAni: number; // = 1; 出场地格子动画效果
    static readonly rangeFieldAni: number; // = 1; 作用范围格子动画效果
    static readonly releaseFieldAni: number; // = 1; 释放范围格子动画效果
    static readonly battleCursorAni: number; // = 1; 光标动画效果
    static readonly hurtAni: number; // = 1; 战斗者受伤时显示的动画
    static showAtkRangeRef: boolean; // = true; 指示器显示攻击范围参考
    static showMoveRange: boolean; // = true; 显示移动指示器
    static battleScene: number; // = 0; 战斗场景
    static battleSceneBGM: string; // = ""; 战斗背景音乐
    static battleSceneEnabled: boolean; // = false; 允许使用战斗画面
    static battleSceneAdvanceSetting: boolean; // = true; 高级设定
    static battlerSpacing: number; // = 75; 战斗者间距
    static battlerSpeed: number; // = 2000; 战斗移动速度
    static cameraToTargetTotalFrame: number; // = 20; 镜头指向目标的帧数
    static bulletOffsetX: number; // = 0; 弹幕发出偏移量X
    static bulletOffsetY: number; // = 0; 弹幕发出偏移量Y
    static waitStartTime: number; // = 0.5; 开始前等待时间
    static battleSceneFlipAniLayer: boolean; // = true; 水平翻转右边战斗者的动画层
    static battleSceneBackwardSupport: boolean; // = true; 攻击敌人的后背
    static battleSceneAutoPosition: number; // = 1; 站位模式
    static battleSceneDisplayStatusAni: boolean; // = true; 显示状态动画
    static extendsAttributeSetting: DataStructure_customAttributeSetting[]; // = [];
    static useCustomDamageLogic: boolean; // = false; 使用自定义伤害计算
    static customDamageLogicEvent: string; // = ""; 自定义伤害逻辑
    static const_fp_game: number; // = 15001; 作品支持度
    static const_fp_user: number; // = 15002; 作者支持度
    static const_fp_cost_value: number; // = 15003; 消耗点数
    static const_fp_changeValue: number; // = 15004; 支持度变化值
    static const_fp_changeEvent: string; // = ""; 当变化时事件
}
class PlayerData {
    sceneObject: SceneObject;
    package: DataStructure_packageItem[]; // = [];
    gold: number; // = 0; 金币
    party: DataStructure_inPartyActor[]; // = [];
    actorRecords: DataStructure_inPartyActor[]; // = [];
    monsterManual_byKDS: number[]; // = [];
}